# Content
excerpt_link: 阅读更多>>
fancybox: true

# Sidebar
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 #- category
 #- tagcloud
 #- archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

avatar: /img/avatar.png
author: Mitsuki
subtitle: 这是签名

menu:
  主页: /
  文章: /archives


subnav:
  Email: "mailto:123@123.com"
  GitHub: "#"
  网易云音乐: "netease"
  Twitter: "#"

language: zh-CN
